services:
  datascience-notebook:
    image: johnsnowlabs/sparknlp:sparknlp_for_healthcare_jupyter
    container_name: sparknlp_healthcare_jupyter
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./notebooks:/notebooks
    ports:
      - "8888:8888"
    env_file:
      - .env
