services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - backend

  web:
    build: .
    command: [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:
    driver: bridge